### ISSUE TITLE
AttributeError: 'gobject.GProps' object has no attribute 'enable_webgl'

### ISSUE THREAD

**Issue by ghost** [thgeorgiou/pPub#1]
Hi,

Just installing today (20111031) on my Slackware/Salix system, I got this error when trying to launch it.

fredg[~]$ ppub
Traceback (most recent call last):
  File "/usr/bin/ppub", line 677, in <module>
    main = MainWindow()
  File "/usr/bin/ppub", line 253, in **init**
    self.viewer = Viewer()
  File "/usr/bin/ppub", line 467, in **init**
    settings.props.enable_webgl = False
AttributeError: 'gobject.GProps' object has no attribute 'enable_webgl'

Deps installed: pygtk, pywekbitgtk, infozip

++

**Comment by oylenshpeegul** [comment]
I had the same problem with Ubuntu. When I commented out that line

```
    # settings.props.enable_webgl = False
```

it started and opened up a window. When I selected File->Open, it opened a file dialog. When I selected an .epub file, it expanded a whole bunch of things in /tmp and then froze. So whatever enable_webgl is, I think we need it. :)

**Comment by Psycojoker** [comment]
Oh, didn't saw this issue. I've send a patch via a pull request to fix this: https://github.com/sakisds/pPub/pull/3

**Comment by thgeorgiou** [comment]
I merged the patch from Psycojoker but I can't test it since I have no computer currently.
Please test it so I can mark this as solved.
And thanks again for applying a fix :)

**Comment by oylenshpeegul** [comment]
Yup, works for me! (I can open a different epub file than the one mentioned in my previous comment). I think this issue can be closed.

**Comment by ghost** [comment]
Confirmed here too.
Good job guys.

++
