### ISSUE TITLE
Port to GTK+2

### ISSUE THREAD

**Issue by GreenLunar** [thgeorgiou/pPub#13]
Is it planned to support GTK+2 and WebKitGTK?

Since most distributions, still, do not have WebKitGTK3 installed nor available, I guess a GTK+2 version of pPub will be easily provided and I hope it will make ePub more prevalent and known.

**Comment by thgeorgiou** [comment]
When I first released this, it was using GTK2. After a little while someone patched it for GTK3 and I thought back then 'Why not?'. I don't think I have the willpower to add compatibility for 2 versions of GTK right now, this serves me well even with the small bugs it has. 

Pull requests are more than welcome though. :)

**Comment by GreenLunar** [comment]
Thank you for your helpful reply.  I did not think of looking back at previous commits.  I assume the relevant commit that made the migration from GTK+2 to GTK+3 is this ad0f27577c6544fdedfdc31ee516ef074ad5cbb9

If you may, please instruct me with first steps on how to optimize code to make both toolkits available while installed or by choosing on "compilation" (well, not really, it's python) process.

**Comment by thgeorgiou** [comment]
I wish I could be more help but I don't really know. This project was my only experience with GTK and I think I am still missing some parts.

I found some ideas about this [here](http://stackoverflow.com/questions/8354964/python-gui-both-compatible-gtk2-and-gtk3), it might help you a bit.
