### ISSUE TITLE
desktop integration

### ISSUE THREAD

**Issue by ghost** [thgeorgiou/pPub#2]
HI,

To make pPub appear in Xfce/Gnome/... menu, we need a .desktop file and an icon.
This is a ppub.desktop file:

```
[Desktop Entry]
Categories=Office;Viewer;
MimeType=application/epub+zip;
Exec=ppub %U
Icon=ppub_48
StartupNotify=false
Terminal=false
Type=Application
Name=pPub
Name[fr]=pPub
Comment=Simple epub ebbok reader
Comment[fr]=Simple lecteur d'ebook au format epub
```

link: http://people.salixos.org/fredg/packages/ppub/20111031/ppub.desktop

The icon is taken from wikipedia as I mention it in my SLKBUILD to create a slackware package.
Those lines can also be added to your PKGBUILD or in an install script.

```
Desktop integration

pPub has no official logo for now, in the meantine I
will use this one found on wikipedia converted to png
 http://en.wikipedia.org/wiki/File:EPUB_logo.svg

this is a logo owned by International Digital
Publication Forum for the EPUB file format. It is a
historical logo. Its historical usage is as follows:
The logo was recently accepted (2010-06) as part of a
competition to create a logo for EPUB. Further
details: Designed by Ralph Burkhardt as part of the
IDPF competition.
    install -Dm 644 $srcdir/ppub_48.png \
        $pkgdir/usr/share/icons/hicolor/48x48/apps/ppub_48.png
    install -Dm 644 $srcdir/ppub.desktop \
        $pkgdir/usr/share/applications/ppub.desktop
```

icons: http://people.salixos.org/fredg/packages/ppub/20111031/

And, btw, thanks for this simple app.

Regards.

fredg

**Comment by thgeorgiou** [comment]
Thanks a lot for writing this. I am currently away from home but I will add this to my PKGBUILD when I am back.

**Comment by thgeorgiou** [comment]
Done, ppub now has an official icon and a .desktop file is in the repository. You might also want to update your slackware package.

**Comment by ghost** [comment]
Great, thank you.

So, to install pPubon Salix:
slapt-src -i ppub

++ fredg

2011/11/7 Thanasis Georgiou
reply@reply.github.com:

> Done, ppub now has an official icon and a .desktop file is in the repository. You might also want to update your slackware package.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sakisds/pPub/issues/2#issuecomment-2658870

## 

Google+: https://plus.google.com/108565419331171281999

**Comment by thgeorgiou** [comment]
If you want to maintain that package, please give me a mail so I can notify you of any packing changes.
Thanks a lot for creating that package.

**Comment by ghost** [comment]
2011/11/22 Thanasis Georgiou
reply@reply.github.com:

> If you want to maintain that package, please give me a mail so I can notify you of any packing changes.
> Nice, here it is: fredg ~at~ salixos ~dot~ org
> 
> Thanks a lot for creating that package.
> No, thank you ;)
> Keep up with good work.

## ++ fredg

Google+: https://plus.google.com/108565419331171281999
