### ISSUE TITLE
Use random path in /tmp

### ISSUE THREAD

**Issue by bigon** [thgeorgiou/pPub#7]
Hi,

It seems that pPub always uses "/tmp/ppub-cache/" as path for uncompressing the .epub.

This is not good as several users may want use the application at the same time.

Please use a random path (maybe with the user name in the path).

Could also be good the restrict the permission of the directory to 700 and to delete it when pPub exits

**Comment by thgeorgiou** [comment]
Done, now the default cache directory is "/tmp/ppub-cache-username" and the permissions of it are 700.
Also it's cleaned on exit.
