### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

### ISSUE THREAD

**Issue by lidaobing** [thgeorgiou/pPub#9]
Traceback (most recent call last):
  File "ppub.py", line 489, in open_book
    self.window.set_title(str(self.provider.book_name)+" by "+str(self.provider.book_author))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by thgeorgiou** [comment]
I think this is happening because the book you are trying to open has encoding problems with it's .opf file. I pushed a commit to catch UnicodeEncodeError but it might get stuck on another point.

**Comment by lidaobing** [comment]
similar error for git HEAD version:
Traceback (most recent call last):
  File "ppub.py", line 588, in open_book
    self.window.set_title(str(self.provider.book_name)+" by "+str(self.provider.book_author))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

and the opf file in https://gist.github.com/1338421 , the encoding is utf-8, 

how about change the default encoding of opf from ascii to utf-8? 

thanks

**Comment by thgeorgiou** [comment]
I changed the default encoding from ascii to utf-8 and reverted the previous change.
Please try again now and tell me if your book's title and author are properly displayed in the title bar after opening.

**Comment by lidaobing** [comment]
it works, thanks.
